set-option -sa terminal-overrides ",xterm*:Tc"

set -g mouse on

set -s escape-time 0

# Use vi to move between panes
setw -g mode-keys vi

set -g default-terminal "tmux-256color"

set -g status-position top

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'catppuccin/tmux#v0.3.0'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-open'
# set -g @plugin 'ofirgall/tmux-browser'


# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

set -g @catppuccin_window_current_number_color "#{@thm_blue}"

set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

set -g status-left " "
set -g @catppuccin_date_time_text " %a %d %b %l:%M%p"
set -g status-right-length 200
set -g status-right "#{E:@catppuccin_status_directory} #{E:@catppuccin_status_session} #{E:@catppuccin_status_date_time} "


# Load catppuccin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux


# Set vi-mode
# set-window-option -g mode-keys vi
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel


# Config for tmux-browser
# set -g @open_browser_key 'B'
# set -g @new_browser_window 'open'

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind-key -n C-l next-window
bind-key -n C-h previous-window

# https://stackoverflow.com/questions/15470001/bind-ctrltab-and-ctrlshifttab-in-tmux
# This is not working at this stage
# set-option -gw xterm-keys on
# bind-key -n C-Tab next-window
# bind-key -n C-S-Tab previous-window

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

bind-key -r f run-shell "tmux neww ~/bin/tmux-session"
bind-key -r g run-shell "tmux neww ~/bin/tmux-window"

